[package]

name = "conduit"
version = "0.8.1"
authors = ["wycats@gmail.com",
           "Alex Crichton <alex@alexcrichton.com>"]
description = "Common HTTP server interface"
license = "MIT"
repository = "https://github.com/conduit-rust/conduit"

[dependencies]
semver = ">= 0.5.0, < 0.10.0"
